const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p); await p.setViewport({ width: 1366, height: 1000 });
  const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => doDemo()); await p.evaluate(() => { location.hash = "#totaux/5"; }); await wait(400);
  const fonds = () => p.evaluate(() => { const c = {}; document.querySelectorAll("table.tot td.pc span").forEach(s => { const bg = getComputedStyle(s).backgroundColor; if (bg !== "rgba(0, 0, 0, 0)") { const k = s.parentElement.classList.contains("p3") ? "rouge" : s.parentElement.classList.contains("p2") ? "orange" : s.parentElement.classList.contains("fonce") ? "vert" : "vertclair"; c[k] = (c[k] || 0) + 1; } }); return c; });
  const cellBg = () => p.evaluate(() => [...document.querySelectorAll("table.tot td.p0, table.tot td.p1")].filter(td => !td.closest("tbody.imp") && !td.closest("tbody.grp")).every(td => getComputedStyle(td).backgroundColor === "rgba(0, 0, 0, 0)"));
  const f0 = await fonds();
  const sous = await p.evaluate(() => [...document.querySelectorAll("table.tot td.pc span")].filter(s => getComputedStyle(s).backgroundColor !== "rgba(0, 0, 0, 0)").every(s => parseInt(s.textContent) < 80));
  ok(!f0.vert && !f0.vertclair && f0.orange > 0 && f0.rouge > 0 && sous && await cellBg(), `sans pastilles vertes : pastilles seulement sous 80 % ${JSON.stringify(f0)}, aucun fond coloré de case`);
  await (await p.$(".sheet")).screenshot({ path: DIR + "/sorties/past-sans.png" });
  await p.click("#tot-verts"); await wait(300);
  const f1 = await fonds();
  const bons = await p.evaluate(() => [...document.querySelectorAll("table.tot td.pc span")].filter(s => getComputedStyle(s).backgroundColor !== "rgba(0, 0, 0, 0)").map(s => parseInt(s.textContent)));
  const verts = await p.evaluate(() => [...document.querySelectorAll("table.tot td.pc.bon")].map(td => [parseInt(td.textContent), td.classList.contains("aI")]));
  ok(verts.length > 0 && verts.every(([v, i]) => v >= 90 && !i) && bons.every(v => v >= 90 || v < 80), `case cochée : pastilles vertes seulement à 90 % et plus sans croix I (${verts.length}) ; rien entre 80 et 89 %`);
  ok(await p.$eval(".legende-past", e => e.textContent.replace(/[\u202F\u00A0]/g, " ").includes("90 % et plus")), "la légende sous le titre mentionne les pastilles vertes");
  await (await p.$(".sheet")).screenshot({ path: DIR + "/sorties/past-verts.png" });
  await p.reload(); await wait(400);
  ok(await p.$eval("#tot-verts", c => c.checked), "le choix est retenu après rechargement");
  const zebra = await p.$eval("table.tot tbody.imp tr", tr => getComputedStyle(tr).backgroundColor);
  ok(zebra !== "rgba(0, 0, 0, 0)", `un élève sur deux grisé (${zebra})`);
  // impression : suit le choix
  const pdf = async nom => { await p.evaluate(() => { document.querySelector("#print-area").innerHTML = `<div class="page sheet">${totauxHTML(5)}</div>`; });
    await p.emulateMediaType("print");
    const r = await p.evaluate(() => { const c = {}; document.querySelectorAll("#print-area table.tot td.pc span").forEach(s => { if (getComputedStyle(s).backgroundColor !== "rgba(0, 0, 0, 0)") { const k = s.parentElement.classList.contains("p3") ? "rouge" : s.parentElement.classList.contains("p2") ? "orange" : s.parentElement.classList.contains("fonce") ? "vert" : "vertclair"; c[k] = (c[k] || 0) + 1; } }); return c; });
    await p.pdf({ path: DIR + `/sorties/${nom}.pdf`, preferCSSPageSize: true }); await p.emulateMediaType("screen"); return r; };
  const i1 = await pdf("past-impr-verts");
  await p.click("#tot-verts"); await wait(300);
  const i0 = await pdf("past-impr-sans");
  ok(i1.vert > 0 && !i0.vert && i0.rouge > 0, `impression en pastilles, qui suit la case : avec ${JSON.stringify(i1)} / sans ${JSON.stringify(i0)}`);
  const pages = n => Number(require("child_process").execSync(`pdfinfo "${DIR}/sorties/${n}.pdf"`).toString().match(/Pages:\s+(\d+)/)[1]);
  ok(pages("past-impr-verts") === 1 && pages("past-impr-sans") === 1, "impression sur une seule page");
  // 8 élèves (mode dense)
  await p.evaluate(() => { while (S.eleves.length < 8) S.eleves.push({ nom: "TEST" + S.eleves.length, debut: "", fin: "" }); commit(); }); await wait(300);
  await p.click("#tot-verts"); await wait(300);
  await pdf("past-impr-8"); ok(pages("past-impr-8") === 1, "8 élèves avec pastilles vertes : toujours une page");
  await p.evaluate(() => { S.eleves.length = 6; commit(); appliquerTheme("sombre"); }); await wait(300);
  await (await p.$(".sheet")).screenshot({ path: DIR + "/sorties/past-sombre.png" });
  await p.evaluate(() => appliquerTheme("clair")); await p.setViewport({ width: 1024, height: 768 }); await wait(300);
  await p.screenshot({ path: DIR + "/sorties/past-1024.png" });
  ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "1024 : pas de défilement horizontal de la page");
  console.log(errs.length ? "ERREURS " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true }); })();
