const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p, {}); await p.setViewport({ width: 1024, height: 768 }); const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { doDemo(); window.__t = []; window.print = () => { window.__t.push([document.title, document.querySelectorAll("#print-area .page").length]); }; location.hash = "#indivtous"; }); await wait(500);
  const r = await p.evaluate(() => ({ lignes: [...document.querySelectorAll(".indiv-parallele table.evol tbody tr")].map(tr => tr.querySelector("th").textContent.trim()), cols: document.querySelectorAll(".indiv-parallele table.evol thead th").length, courbes: document.querySelectorAll(".indiv-parallele svg polyline").length, avis: [...document.querySelectorAll(".indiv-parallele .avis-chip")].map(x => x.textContent) }));
  console.log(JSON.stringify(r));
  ok(r.lignes.join() === "BRIDGE Michael,MOSTOWSKI Michał,PODEANU Mihaela" && r.courbes >= 3, "menu « Tous les suivis » : une ligne et une courbe par élève suivi");
  ok(r.cols >= 8 && r.avis.join() === "Maintien conseillé,Fin du suivi envisageable,Maintien nécessaire", "une colonne par semaine, tendance et avis de chacun : " + r.avis.join(" · "));
  const lien = await p.$eval(".indiv-parallele table.evol tbody tr:nth-child(3) td a", a => a.getAttribute("href"));
  await p.click(".indiv-parallele table.evol tbody tr:nth-child(3) td a"); await wait(400);
  ok(await p.evaluate(h => location.hash === h && h.startsWith("#indiv/demo-podeanu:"), lien), "clic sur une pastille : la fiche de cet élève pour cette semaine (" + lien + ")");
  await p.evaluate(() => { location.hash = "#indivtous"; }); await wait(400);
  await p.click('[data-act="print-parallele"]'); await wait(300);
  const t = await p.evaluate(() => window.__t.pop());
  ok(/^Suivi 5E - Suivi individuel - Tous les suivis - semaines 45 à 51 du 02-11-2026 au 18-12-2026$/.test(t[0]) && t[1] === 1, "impression : 1 page, « " + t[0] + " »");
  ok(await p.evaluate(() => document.documentElement.scrollWidth <= 1024), "pas de défilement horizontal de la page à 1024 px");
  await p.evaluate(() => document.querySelector(".indiv-parallele").scrollIntoView()); await wait(200); await p.screenshot({ path: DIR + "/sorties/parallele.png" });
  await p.evaluate(() => { window.aujourdhui = () => "2026-12-18";   /* jour de remise : la fiche de la semaine compte */ location.hash = "#indiv"; }); await wait(400);
  const cartes = await p.evaluate(() => [...document.querySelectorAll(".ind-carte.ic2")].map(c => [c.classList.contains("fin") ? "fin" : c.classList.contains("alerte") ? "alerte" : "maintien", c.querySelector(".ic-val").textContent, c.querySelectorAll(".ic-obj").length, !!c.querySelector("svg.spark"), c.querySelector(".ic-pied").textContent.includes("remise le")]));
  console.log(JSON.stringify(cartes));
  ok(cartes.length === 3 && cartes.every(c => /%/.test(c[1]) && c[2] >= 2 && c[3] && c[4]) && cartes.map(c => c[0]).join() === "maintien,fin,alerte", "Fiches individuelles : cartes enrichies (couleur de l’avis, réussite en grand, mini-courbe, barres par objectif, prochaine remise)");
  console.log(errs.length ? "ERREURS JS : " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true });
})();
