const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p); const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { doDemo(); window.__titres = []; window.print = () => window.__titres.push(document.title); });
  const titre = async (avant, action) => { await p.evaluate(avant); await wait(300); await p.evaluate(action); await wait(150); return p.evaluate(() => window.__titres[window.__titres.length - 1]); };
  const vus = {};
  vus.jour = await titre(() => { location.hash = "#fiche/2026-10-12"; }, () => document.querySelector('.imprimer-groupe > button[data-act="print-day"]').click());
  vus.semaine = await titre(() => {}, () => document.querySelector('#m-print [data-act="print-week"]').click());
  vus.periode = await titre(() => {}, () => { const du = document.querySelector("#pr-du"), au = document.querySelector("#pr-au"); du.value = "2026-11-16"; du.dispatchEvent(new Event("change", { bubbles: true })); au.value = "2026-12-04"; au.dispatchEvent(new Event("change", { bubbles: true })); imprimerPeriode(); });
  vus.totaux = await titre(() => { location.hash = "#totaux/5"; }, () => document.querySelector('[data-act="print-tot"]').click());
  vus.bilan = await titre(() => { location.hash = "#bilan"; }, () => document.querySelector('[data-act="print-bilan"]').click());
  vus.bilanPer = await titre(() => { periodeBilan = [2, 2]; render(); }, () => document.querySelector('[data-act="print-bilan"]').click());
  vus.edt = await titre(() => { location.hash = "#edt"; }, () => document.querySelector('[data-act="print-edt"]').click());
  vus.ctrlp = await titre(() => { location.hash = "#totaux/2"; }, () => imprimerVue());
  const apres = await p.evaluate(() => document.title);
  for (const [k, v] of Object.entries(vus)) console.log(`   ${k.padEnd(9)} « ${v} »`);
  ok(vus.jour === "Suivi 5E - Suivi collectif - Fiche du jour - lundi 12-10-2026", "fiche du jour");
  ok(vus.semaine === "Suivi 5E - Suivi collectif - Fiches - semaine 42 du 12-10-2026 au 16-10-2026", "fiches de la semaine");
  ok(vus.periode === "Suivi 5E - Suivi collectif - Fiches - du 16-11-2026 au 04-12-2026", "fiches d’une période");
  ok(/^Suivi 5E - Suivi collectif - Totaux - semaine 49 du 30-11-2026 au 04-12-2026$/.test(vus.totaux), "totaux");
  ok(/^Suivi 5E - Suivi collectif - Bilan par matière - semaines 42 à 51 du 12-10-2026 au 18-12-2026$/.test(vus.bilan) && /^Suivi 5E - Suivi collectif - Bilan par matière - semaine 46 du /.test(vus.bilanPer), "bilan (toute la période, puis une semaine)");
  ok(vus.edt === "Suivi 5E - Emploi du temps - semaines A et B" && /^Suivi 5E - Suivi collectif - Totaux - semaine 46/.test(vus.ctrlp), "emploi du temps, et Ctrl+P sur les totaux");
  ok(!/^Suivi 5E - /.test(apres), `titre habituel remis après l’impression (« ${apres} »)`);
  ok(Object.values(vus).every(v => !/[\\/:*?"<>|]/.test(v)), "aucun caractère interdit dans un nom de fichier");
  console.log(errs.length ? "ERREURS " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true }); })();
