const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p, {}); await p.setViewport({ width: 1024, height: 768 });
  const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.evaluateOnNewDocument(() => { window.__copies = []; Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async t => { window.__copies.push({ "text/plain": t }); }, write: async items => { for (const it of items) { const o = {}; for (const t of it.types) o[t] = await (await it.getType(t)).text(); window.__copies.push(o); } } } }); });
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => doDemo()); await new Promise(r => setTimeout(r, 200));
  await p.evaluate(() => { location.hash = "#indiv/demo-bridge:2026-11-20"; }); await wait(400);
  await p.click('[data-act="copier-objet"]'); await wait(300);
  await p.click('[data-act="copier-message"]'); await wait(300);
  const c = await p.evaluate(() => window.__copies);
  ok(c.length === 2 && c[0]["text/plain"] === "Suivi de Michael BRIDGE – bilan du lundi 16 novembre au vendredi 20 novembre 2026", "« Copier l’objet » : " + (c[0] && c[0]["text/plain"]));
  ok(c[1] && /<table/.test(c[1]["text/html"]) && /background:#/.test(c[1]["text/html"]) && /Remarques des enseignants/.test(c[1]["text/html"]) && /Bilan du professeur principal/.test(c[1]["text/html"]), "« Copier le message » : texte mis en forme (tableau des objectifs avec pastilles, remarques, bilan)");
  ok(c[1] && /^Bonjour,\n\nVoici le bilan du suivi de Michael BRIDGE/.test(c[1]["text/plain"]) && /1\. .* : \d+ % de réussite/.test(c[1]["text/plain"].replace(/[\u202F\u00A0]/g, " ")) && /M\. ROUGET$/.test(c[1]["text/plain"]), "… et aussi en texte brut");
  console.log(c[1] && c[1]["text/plain"]);
  ok(await p.evaluate(() => document.querySelector(".apercu-courriel .msg table") !== null), "« Voir le message » : aperçu mis en forme");
  // repli sans l'API presse-papiers
  await p.evaluate(() => { Object.defineProperty(navigator, "clipboard", { configurable: true, value: undefined }); window.__exec = 0; const o = document.execCommand.bind(document); document.execCommand = c => { if (c === "copy") { window.__exec++; window.__sel = getSelection().toString(); return true; } return o(c); }; });
  await p.click('[data-act="copier-message"]'); await wait(300);
  ok(await p.evaluate(() => window.__exec === 1 && window.__sel.includes("Remarques des enseignants")), "sans l’API du presse-papiers : copie par sélection");
  await p.evaluate(() => { location.hash = "#reglages/suivisIndiv"; }); await wait(400);
  ok(await p.evaluate(() => document.querySelector(".apercu-courriel .msg table") !== null && document.querySelector('textarea[data-path="courrielIndiv.texte"]').value.includes("[bilan]")), "réglages : modèle avec [bilan] et aperçu mis en forme");
  await p.evaluate(() => { location.hash = "#indiv/demo-bridge:2026-11-20"; }); await wait(300);
  await p.evaluate(() => { document.querySelector("details.apercu-courriel").open = true; document.querySelector("details.apercu-courriel").scrollIntoView(); }); await wait(200);
  await p.screenshot({ path: DIR + "/sorties/courriel.png" });
  console.log(errs.length ? "ERREURS JS : " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true });
})();
