const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); const msgs = []; let choix = "HASHIMOTO Mika"; await require("./boites")(p, { messages: msgs, reponse: () => choix }); await p.setViewport({ width: 1366, height: 900 });
  const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { doDemo(); window.__titres = []; window.print = () => window.__titres.push(document.title); }); await wait(200);
  const go = async h => { await p.evaluate(h => { location.hash = h; }, h); await wait(300); };
  const D = "2026-11-17";
  // ---------- fiche de classe ----------
  await go("#fiche/" + D);
  ok(await p.$eval('#tabs a[data-v="fiche"] span', e => e.textContent) === "Fiches collectives", "menu : onglet « Fiches collectives »");
  await p.click('#tabs a[data-v="classe"]'); await wait(400);
  ok(await p.evaluate(() => location.hash === "#classesem" && document.querySelectorAll("table.cs thead th.cs-nom").length === 26 && document.querySelector('#tabs a[data-v="classe"]').classList.contains("on") && !document.querySelector('.seg[aria-label^="Fiche de classe par jour"]')), "« Fiches de classe » : la fiche de la semaine (26 élèves), plus de vue par jour");
  await go("#classe/" + D);
  ok(await p.evaluate(() => location.hash === "#classesem/3" && document.querySelector(".page-tete h1").textContent.startsWith("Semaine 47")), "ancienne adresse #classe/17-11 : fiche de la semaine 47");
  const cel = `td[data-cl="2.0"][data-d="${D}"]`;
  await p.evaluate(D => { delete S.jours[D].cl["2.0"]; commit(); }, D); await wait(200);
  await p.click('[data-pal-cl="?"]'); await wait(100);
  await p.click(cel); await wait(250);
  ok(await p.evaluate(() => !document.querySelector("#pop-cl").hidden && document.querySelectorAll("#pop-cl [data-clcode]").length === 7), "clic sur une case : choix des 7 codes (6 + absent)");
  await p.click('#pop-cl [data-clcode="B"]'); await wait(200); await p.click('#pop-cl [data-clcode="T"]'); await wait(200);
  ok(await p.evaluate(D => S.jours[D].cl["2.0"] === "BT" && !document.querySelector("#pop-cl").hidden, D), "B puis T : la case contient « BT », la petite fenêtre reste ouverte");
  await p.click('#pop-cl [data-clcode="A"]'); await wait(200);
  ok(await p.evaluate(D => S.jours[D].cl["2.0"] === "A", D), "« absent » remplace les autres codes");
  await p.keyboard.press("Escape"); await wait(200);
  ok(await p.evaluate(D => document.querySelector("#pop-cl").hidden && document.activeElement.dataset.cl === "2.0" && document.activeElement.dataset.d === D, D), "Échap ferme, le focus reste sur la case");
  await p.keyboard.press("ArrowDown"); await wait(100); await p.keyboard.press("m"); await wait(200);
  ok(await p.evaluate(D => document.activeElement.dataset.cl === "2.1" && S.jours[D].cl["2.1"].includes("M"), D), "au clavier : flèche ↓ (cours suivant) puis « m » : code M posé");
  await p.keyboard.press("Delete"); await wait(200);
  ok(await p.evaluate(D => !S.jours[D].cl["2.1"], D), "Suppr vide la case");
  await p.evaluate(() => document.activeElement.blur()); await p.keyboard.press("ArrowRight"); await wait(300);
  ok(await p.evaluate(() => location.hash === "#classesem/4"), "touche → : semaine suivante");
  await p.evaluate(() => imprimerVue()); await wait(100);
  ok((await p.evaluate(() => window.__titres.pop())) === "Suivi 5E - Classe entière - Fiche de la semaine - semaine 48 du 23-11-2026 au 27-11-2026", "Ctrl+P : « Suivi 5E - Classe entière - Fiche de la semaine - semaine 48 du … »");
  // réglages : retirer un élève de la classe décale ses codes
  await p.evaluate(() => { S.jours["2026-11-18"].cl = { "0.0": "B", "1.0": "T" }; commit(); });
  await go("#reglages/classeEntiere");
  ok(await p.evaluate(() => document.querySelectorAll(".liste.lcl .lrow").length === 26), "Réglages › Élèves et groupes : 26 élèves");
  msgs.length = 0; await p.click('button[data-del="classeEleves.0"]'); await wait(400);
  ok(await p.evaluate(() => S.classeEleves.length === 25 && S.jours["2026-11-18"].cl["0.0"] === "T" && !S.jours["2026-11-18"].cl["1.0"]) && msgs.some(m => m.includes("Supprimer un élève de la classe")), "retirer le 1er élève : confirmation, les codes des suivants remontent");
  await p.evaluate(() => { location.hash = "#reglages/ficheClasse"; }); await wait(300);
  await p.$eval('input[data-path="codesClasse.0.code"]', i => { i.value = "a"; i.dispatchEvent(new Event("change", { bubbles: true })); }); await wait(200);
  ok(await p.evaluate(() => S.codesClasse[0].code === "B"), "code « a » refusé (réservé à « absent »)");
  await p.$eval('input[data-path="codesClasse.0.code"]', i => { i.value = "x"; i.dispatchEvent(new Event("change", { bubbles: true })); }); await wait(200);
  ok(await p.evaluate(() => S.codesClasse[0].code === "X" && S.jours["2026-11-18"].cl["0.0"] === "T" && Object.values(S.jours).some(j => Object.values(j.cl || {}).some(v => v.includes("X"))) && !Object.values(S.jours).some(j => Object.values(j.cl || {}).some(v => v.includes("B")))), "code « x » enregistré en majuscule ; les « B » déjà saisis deviennent « X »");
  // ---------- suivis individuels ----------
  await go("#indiv");
  ok(await p.evaluate(() => document.querySelectorAll(".ind-carte").length === 3), "Suivis individuels : 3 élèves suivis");
  await p.click('a.ind-carte[href="#indiv/demo-bridge"]'); await wait(300);
  await p.evaluate(() => { location.hash = "#indiv/demo-bridge:2026-11-20"; }); await wait(300);
  ok(await p.evaluate(() => !document.querySelector("details.reg-ind").open), "réglages du suivi : repliés dans un menu");
  await p.click("details.reg-ind > summary"); await wait(200);
  const cle = await p.evaluate(() => { const td = document.querySelector('td[data-ic^="0.2026-11-16.0"]'); return td.dataset.ic; });
  await p.evaluate(c => { const [ii, d, pp] = c.split("."); delete S.individuels[ii].saisies[`${d}.${pp}`]; commit(); }, cle); await wait(200);
  await p.click(`td[data-ic="${cle}"]`); await wait(200); await p.click('[data-pal-ind="0"]'); await wait(200);
  ok(await p.evaluate(c => { const [ii, d, pp, o] = c.split("."); return S.individuels[ii].saisies[`${d}.${pp}`].c[o] === 0; }, cle), "clic sur la case, puis TB dans la palette : TB écrit");
  await p.click('[data-pal-ind="0"]'); await wait(150); await p.focus(`td[data-ic="${cle}"]`); await p.keyboard.press("1"); await wait(200);
  ok(await p.evaluate(c => { const [ii, d, pp, o] = c.split("."); return S.individuels[ii].saisies[`${d}.${pp}`].c[o] === 3 && document.activeElement.dataset.ic === `${ii}.${d}.${pp}.1`; }, cle), "touche 1 (le plus faible) : I, puis la case de l’objectif suivant");
  await p.keyboard.press("Backspace"); await wait(200);
  ok(await p.evaluate(c => { const [ii, d, pp, o] = c.split("."); return !S.individuels[ii].saisies[`${d}.${pp}`] && document.activeElement.dataset.ic === c; }, cle), "Retour arrière : la case précédente est vidée et reprise");
  await p.keyboard.press("2"); await wait(200);
  const ir = cle.split(".").slice(0, 3).join(".");
  await p.type(`input[data-ir="${ir}"]`, "Oubli de cahier"); await p.keyboard.press("Tab"); await wait(200);
  ok(await p.evaluate(ir => { const [ii, d, pp] = ir.split("."); return S.individuels[ii].saisies[`${d}.${pp}`].r === "Oubli de cahier"; }, ir), "remarque du cours enregistrée");
  await p.click('[data-io="add.0"]'); await wait(300); await p.keyboard.type("Je range mes affaires."); await p.keyboard.press("Tab"); await wait(200);
  ok(await p.evaluate(() => S.individuels[0].objectifs.length === 4 && S.individuels[0].objectifs[3] === "Je range mes affaires." && Object.values(S.individuels[0].saisies).every(s => s.c.length === 4)), "4e objectif ajouté et saisi ; les saisies ont une case de plus");
  msgs.length = 0; await p.click('[data-io="del.0.0"]'); await wait(400);
  ok(await p.evaluate(() => S.individuels[0].objectifs.length === 3 && S.individuels[0].objectifs[0].startsWith("Je lève")) && msgs.some(m => m.includes("Supprimer l’objectif")), "supprimer l’objectif 1 (déjà saisi) : confirmation, les autres remontent");
  await p.evaluate(() => imprimerVue()); await wait(100);
  ok((await p.evaluate(() => window.__titres.pop())) === "Suivi 5E - Suivi individuel - BRIDGE Michael - Fiche - semaine 47 du 16-11-2026 au 20-11-2026", "impression : nom « Suivi 5E - Suivi individuel - BRIDGE Michael - du 16-11-2026 au 20-11-2026 »");
  await p.click('[data-act="print-famille"]'); await wait(200);
  ok((await p.evaluate(() => [window.__titres.pop(), document.querySelectorAll("#print-area .page").length, !!document.querySelector("#print-area .bilan-famille")]))[0] === "Suivi 5E - Suivi individuel - BRIDGE Michael - Bilan pour la famille - semaine 47 du 16-11-2026 au 20-11-2026", "« Bilan pour la famille (PDF) » : nom du PDF « Suivi 5E - Bilan pour la famille - BRIDGE Michael - … »");
  const mail = await p.$eval('a.btn[href^="mailto:"]', a => decodeURIComponent(a.getAttribute("href")));
  ok(mail.startsWith("mailto:famille.bridge@exemple.fr?subject=Suivi de Michael BRIDGE") && mail.includes("bilan du suivi"), "« Écrire à la famille » : courriel préparé (destinataire, objet, message)");
  await go("#indiv/demo-mostowski");
  const cy = await p.evaluate(() => cyclesIndiv(S.individuels[1]).map(c => c.debut.slice(5) + ">" + c.fin.slice(5)).slice(0, 3).join(" "));
  ok(cy === "11-16>11-19 11-20>11-26 11-27>12-03", `remise le jeudi : fiches du vendredi au jeudi (${cy})`);
  await p.select('select[data-num="individuels.1.remise"]', "5"); await wait(300);
  ok(await p.evaluate(() => S.individuels[1].remise === 5 && cyclesIndiv(S.individuels[1])[1].fin === "2026-11-27"), "remise passée au vendredi : les fiches vont du lundi au vendredi");
  await go("#indiv"); await p.click('[data-act="ind-ajout"]'); await wait(600);
  ok(await p.evaluate(() => S.individuels.length === 4 && S.individuels[3].nom === "HASHIMOTO Mika" && location.hash.startsWith("#indiv/")), "nouveau suivi individuel : élève choisi dans la liste de la classe, page ouverte");
  // ---------- enregistrement ----------
  const rt = await p.evaluate(() => { const a = JSON.stringify(S), b2 = JSON.stringify(normalizeState(JSON.parse(a))); return a === b2 || [a.length, b2.length]; });
  ok(rt === true, "le suivi (fiche de classe, suivis individuels) se relit à l’identique depuis le .json " + (rt === true ? "" : JSON.stringify(rt)));
  console.log(errs.length ? "ERREURS " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true }); })();
