const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p, {}); await p.setViewport({ width: 1024, height: 768 }); const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { doDemo(); window.__t = []; window.print = () => { window.__t.push([document.title, document.querySelectorAll("#print-area .page").length]); }; location.hash = "#indiv/demo-bridge"; }); await wait(500);
  const r = await p.evaluate(() => ({ mats: [...document.querySelectorAll(".bmi-carte table.bmi tbody th.l")].map(t => t.childNodes[0].textContent.trim()), faibles: [...document.querySelectorAll(".bmi-carte tr.faible th.l")].map(t => t.childNodes[0].textContent.trim()), alerte: (document.querySelector(".bmi-carte .avis") || {}).textContent, cols: document.querySelectorAll(".bmi-carte table.bmi thead th").length, n: serieIndiv(S.individuels[0]).length }));
  console.log(JSON.stringify(r));
  ok(r.mats.length >= 8 && r.mats.includes("Mathématiques") && r.mats.includes("Latin") && r.cols === r.n + 4, "bilan par matière de BRIDGE : une ligne par matière (Latin compris, son option), une colonne par fiche + période, écart, tendance");
  /* les lignes du tableau suivent l'ordre des champs disciplinaires (2026-10-11) : c'est l'ALERTE qui classe par écart */
  ok(r.faibles.includes("Mathématiques") && /^Nettement moins bien en Mathématiques/.test(r.alerte), "tous objectifs : « Nettement moins bien en Mathématiques » signalé en premier");
  await p.select('select[data-bmo="demo-bridge"]', "0"); await wait(400);
  const r1 = await p.evaluate(() => ({ faibles: [...document.querySelectorAll(".bmi-carte tr.faible th.l")].map(t => t.childNodes[0].textContent.trim()), alerte: (document.querySelector(".bmi-carte .avis") || {}).textContent }));
  console.log(JSON.stringify(r1));
  ok(r1.faibles.includes("Mathématiques") && /Nettement moins bien en Mathématiques/.test(r1.alerte), "objectif ① seul : les maths ressortent aussi");
  const tot = await p.evaluate(() => { const x = bilanMatiereIndiv(S.individuels[0], -1); return [x.mats.reduce((a, m) => a + m.tot[1], 0), serieIndiv(S.individuels[0]).reduce((a, f) => a + f.st.reduce((b, s) => b + s[1], 0), 0)]; });
  ok(tot[0] === tot[1], "toutes les matières réunies = tous les codes des fiches (" + tot.join(" = ") + ")");
  await p.click('[data-act="print-bmi"]'); await wait(300);
  const t = await p.evaluate(() => window.__t.pop());
  ok(/^Suivi 5E - Suivi individuel - BRIDGE Michael - Bilan par matière - du 02-11-2026 au /.test(t[0]) && t[1] === 1, "impression : 1 page « " + t[0] + " »");
  await p.click('[data-act="print-evol"]'); await wait(300);
  ok(await p.evaluate(() => window.__t.pop()[1] === 2), "« Imprimer l’évolution » : évolution + bilan par matière (2 pages)");
  ok(await p.evaluate(() => document.documentElement.scrollWidth <= 1024), "pas de défilement horizontal à 1024 px");
  await p.evaluate(() => document.querySelector(".bmi-carte").scrollIntoView()); await wait(200); await p.screenshot({ path: DIR + "/sorties/bmi.png" });
  console.log(errs.length ? "ERREURS JS : " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true });
})();
