const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p, {}); await p.setViewport({ width: 1024, height: 768 }); const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { window.aujourdhui = () => "2026-11-17"; doDemo(); window.__t = []; window.print = () => { window.__t.push(document.title); }; }); await wait(400);
  const r = await p.evaluate(() => ({ cartes: document.querySelectorAll(".sf-sem").length, vac: document.querySelectorAll(".sf-vac").length, on: document.querySelector(".sf-sem.on b").textContent, jours: document.querySelectorAll(".somm-sem .somm-jour").length, lignes: document.querySelectorAll("table.somm-el tbody tr").length, colOn: document.querySelector("table.somm-el thead th.on").textContent }));
  console.log(JSON.stringify(r));
  ok(r.cartes === 8 && r.vac === 1, "frise : 8 semaines, les vacances de la Toussaint entre deux");
  ok(r.on === "Semaine 47" && r.colOn === "S47", "semaine en cours choisie par défaut (le 17/11 : semaine 47), colonne surlignée");
  ok(r.jours === 5 && r.lignes === 7, "bandeau : les 5 jours ; tableau : 6 élèves + le groupe");
  await p.click('.sf-sem[data-sem="5"]'); await wait(400);
  ok(await p.evaluate(() => location.hash === "#sommaire/5" && document.querySelector(".sf-sem.on b").textContent === "Semaine 49" && document.querySelector("table.somm-el thead th.on").textContent === "S49"), "clic sur une carte : semaine 49 choisie, bandeau et colonne suivent");
  await p.keyboard.press("ArrowLeft"); await wait(400);
  ok(await p.evaluate(() => location.hash === "#sommaire/4"), "flèche ← : semaine précédente");
  await p.click('.somm-sem [data-act="print-week"]'); await wait(200);
  ok((await p.evaluate(() => window.__t.pop())) === "Suivi 5E - Suivi collectif - Fiches - semaine 48 du 23-11-2026 au 27-11-2026", "« Fiches de la semaine 48 » : nom du PDF");
  await p.click(".somm-sem .somm-jour"); await wait(400);
  ok(await p.evaluate(() => location.hash === "#fiche/2026-11-23"), "clic sur un jour : sa fiche collective");
  await p.evaluate(() => { location.hash = "#sommaire/3"; }); await wait(300);
  await p.click("table.somm-el tbody tr:nth-child(2) td:nth-of-type(3) a"); await wait(400);
  ok(await p.evaluate(() => location.hash === "#totaux/2"), "clic sur une pastille : totaux de cette semaine");
  await p.evaluate(() => { location.hash = "#sommaire/3"; }); await wait(300);
  ok(await p.evaluate(() => document.documentElement.scrollWidth <= 1024), "pas de défilement horizontal de la page à 1024 px");
  await p.screenshot({ path: DIR + "/sorties/sommaire-E.png" });
  console.log(errs.length ? "ERREURS JS : " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true });
})();
