const puppeteer = require("/usr/local/lib/node_modules/puppeteer"); const fs = require("fs"); const DIR = __dirname;
const ok = (c, m) => console.log((c ? "OK   " : "ÉCHEC") + " " + m);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const prof = fs.mkdtempSync(DIR + "/sorties/chrome-tmp-");
  const b = await puppeteer.launch({ executablePath: "/opt/google/chrome/chrome", headless: true, userDataDir: prof, args: ["--no-sandbox"] });
  const p = await b.newPage(); await require("./boites")(p, {}); await p.setViewport({ width: 1024, height: 768 });
  const errs = []; p.on("pageerror", e => errs.push(e.message));
  await p.goto("file://" + DIR + "/app/Fiche de suivi collective.html"); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => doDemo()); await wait(200);
  await p.evaluate(() => { window.__titres = []; const o = window.print; window.print = () => { window.__titres.push(document.title); window.__pages = document.querySelectorAll("#print-area .page").length; }; });
  const go = async h => { await p.evaluate(h => { location.hash = h; }, h); await wait(400); };
  await go("#indiv");
  const chips = await p.$$eval(".ind-carte .avis-chip", e => e.map(x => x.textContent));
  console.log("avis :", chips.join(" | "));
  ok(chips.length === 3 && chips[1] === "Fin du suivi envisageable" && chips[2] === "Maintien nécessaire" && chips[0] !== chips[1], "liste des suivis : avis sur le maintien pour chaque élève");
  await go("#indiv/demo-mostowski");
  const r = await p.evaluate(() => ({ cols: document.querySelectorAll(".evol-indiv:not(.bmi-carte) table.evol thead th").length, lignes: document.querySelectorAll(".evol-indiv:not(.bmi-carte) table.evol tbody tr").length, avis: document.querySelector(".evol-indiv .avis b").textContent, pts: document.querySelectorAll("svg.courbe-indiv :is(circle, rect, path):has(title)").length, n: serieIndiv(S.individuels[1]).length }));
  console.log(JSON.stringify(r));
  ok(r.cols === r.n + 2 && r.lignes === 2 + 2, `tableau : une colonne par fiche (${r.n}) + tendance ; objectifs, ensemble, cours notés`);
  ok(r.avis === "Fin du suivi envisageable" && r.pts >= r.n * 2 - 1, "MOSTOWSKI : objectifs atteints → fin du suivi envisageable ; courbes tracées");
  await go("#indiv/demo-bridge");
  const rb = await p.evaluate(() => [document.querySelector(".evol-indiv .avis b").textContent, document.querySelector(".evol-indiv .avis").textContent.includes("pts")]);
  ok(/Maintien/.test(rb[0]) && rb[1], "BRIDGE : " + rb[0] + " (avec tendances en points)");
  ok(await p.evaluate(() => { const e = document.querySelector(".evol-defil"); return e.scrollLeft >= 0 && document.documentElement.scrollWidth <= 1024; }), "pas de défilement horizontal de la page à 1024 px");
  await p.evaluate(() => document.querySelector(".evol-indiv").scrollIntoView()); await wait(150); await p.screenshot({ path: DIR + "/sorties/evol.png" });
  await p.click('[data-act="print-evol"]'); await wait(300);
  const t = await p.evaluate(() => [window.__titres.pop(), window.__pages]);
  ok(/^Suivi 5E - Suivi individuel - BRIDGE Michael - Évolution - du 02-11-2026 au /.test(t[0]) && t[1] === 2, "impression de l’évolution : 2 pages (évolution + bilan par matière), " + t[0]);
  // réglage : seuil plus exigeant
  await go("#reglages/suivisIndiv");
  await p.$eval('input[data-num="finSuiviIndiv.seuil"]', i => { i.value = "100"; i.dispatchEvent(new Event("change", { bubbles: true })); }); await wait(300);
  ok(await p.evaluate(() => S.finSuiviIndiv.seuil === 100 && avisMaintien(S.individuels[1]).niv !== "fin"), "seuil à 100 % : MOSTOWSKI n’est plus « fin envisageable »");
  await p.$eval('input[data-num="finSuiviIndiv.seuil"]', i => { i.value = "20"; i.dispatchEvent(new Event("change", { bubbles: true })); }); await wait(300);
  ok(await p.evaluate(() => S.finSuiviIndiv.seuil === 50), "seuil trop bas ramené à 50 %");
  await p.click('input[data-bool="finSuiviIndiv.sansI"]'); await wait(300);
  ok(await p.evaluate(() => S.finSuiviIndiv.sansI === false), "case « sans I » décochée");
  console.log(errs.length ? "ERREURS JS : " + errs.join(" | ") : "aucune erreur JS");
  await b.close(); fs.rmSync(prof, { recursive: true, force: true });
})();
